### ISSUE TITLE
"Error: Project not found!" when trying to do anything

### ISSUE THREAD

**Issue by aleksrutins** [railwayapp/cliv3#9]
When trying to use `railway run` or `railway shell`, I get a project not found error despite the fact that I just linked my current directory to a project.
![image](https://user-images.githubusercontent.com/24496030/220471086-3b2aa7fd-effe-47d9-a6c1-d1710ab9f615.png)

**Comment by nebulatgs** [comment]
Fixed in `v0.0.3`!
